// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.share.core.protocol.protobuf.demo;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ReqDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.share.core.protocol.protobuf.demo.ReqDemo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    int getProtocol();

    /**
     * <code>optional sint32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code com.share.core.protocol.protobuf.demo.ReqDemo}
   */
  public  static final class ReqDemo extends
      com.google.protobuf.GeneratedMessageLite<
          ReqDemo, ReqDemo.Builder> implements
      // @@protoc_insertion_point(message_implements:com.share.core.protocol.protobuf.demo.ReqDemo)
      ReqDemoOrBuilder {
    private ReqDemo() {
      name_ = "";
      email_ = "";
    }
    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private int protocol_;
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    public int getProtocol() {
      return protocol_;
    }
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    private void setProtocol(int value) {
      
      protocol_ = value;
    }
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    private void clearProtocol() {
      
      protocol_ = 0;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional sint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional sint32 id = 2;</code>
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>optional sint32 id = 2;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.String name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 3;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.String email_;
    /**
     * <code>optional string email = 4;</code>
     */
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocol_ != 0) {
        output.writeSInt32(1, protocol_);
      }
      if (id_ != 0) {
        output.writeSInt32(2, id_);
      }
      if (!name_.isEmpty()) {
        output.writeString(3, getName());
      }
      if (!email_.isEmpty()) {
        output.writeString(4, getEmail());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (protocol_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, protocol_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, id_);
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getEmail());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.share.core.protocol.protobuf.demo.Demo.ReqDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.share.core.protocol.protobuf.demo.ReqDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.share.core.protocol.protobuf.demo.Demo.ReqDemo, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.share.core.protocol.protobuf.demo.ReqDemo)
        com.share.core.protocol.protobuf.demo.Demo.ReqDemoOrBuilder {
      // Construct using com.share.core.protocol.protobuf.demo.Demo.ReqDemo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public int getProtocol() {
        return instance.getProtocol();
      }
      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public Builder setProtocol(int value) {
        copyOnWrite();
        instance.setProtocol(value);
        return this;
      }
      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public Builder clearProtocol() {
        copyOnWrite();
        instance.clearProtocol();
        return this;
      }

      /**
       * <code>optional sint32 id = 2;</code>
       */
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>optional sint32 id = 2;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>optional sint32 id = 2;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional string email = 4;</code>
       */
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.share.core.protocol.protobuf.demo.ReqDemo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.share.core.protocol.protobuf.demo.Demo.ReqDemo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.share.core.protocol.protobuf.demo.Demo.ReqDemo other = (com.share.core.protocol.protobuf.demo.Demo.ReqDemo) arg1;
          protocol_ = visitor.visitInt(protocol_ != 0, protocol_,
              other.protocol_ != 0, other.protocol_);
          id_ = visitor.visitInt(id_ != 0, id_,
              other.id_ != 0, other.id_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  protocol_ = input.readSInt32();
                  break;
                }
                case 16: {

                  id_ = input.readSInt32();
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.share.core.protocol.protobuf.demo.Demo.ReqDemo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.share.core.protocol.protobuf.demo.ReqDemo)
    private static final com.share.core.protocol.protobuf.demo.Demo.ReqDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReqDemo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.share.core.protocol.protobuf.demo.Demo.ReqDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ReqDemo> PARSER;

    public static com.google.protobuf.Parser<ReqDemo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ResDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.share.core.protocol.protobuf.demo.ResDemo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    int getProtocol();

    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code com.share.core.protocol.protobuf.demo.ResDemo}
   */
  public  static final class ResDemo extends
      com.google.protobuf.GeneratedMessageLite<
          ResDemo, ResDemo.Builder> implements
      // @@protoc_insertion_point(message_implements:com.share.core.protocol.protobuf.demo.ResDemo)
      ResDemoOrBuilder {
    private ResDemo() {
      email_ = "";
    }
    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private int protocol_;
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    public int getProtocol() {
      return protocol_;
    }
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    private void setProtocol(int value) {
      
      protocol_ = value;
    }
    /**
     * <code>optional sint32 protocol = 1;</code>
     */
    private void clearProtocol() {
      
      protocol_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.String email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocol_ != 0) {
        output.writeSInt32(1, protocol_);
      }
      if (!email_.isEmpty()) {
        output.writeString(2, getEmail());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (protocol_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, protocol_);
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmail());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.share.core.protocol.protobuf.demo.Demo.ResDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.share.core.protocol.protobuf.demo.ResDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.share.core.protocol.protobuf.demo.Demo.ResDemo, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.share.core.protocol.protobuf.demo.ResDemo)
        com.share.core.protocol.protobuf.demo.Demo.ResDemoOrBuilder {
      // Construct using com.share.core.protocol.protobuf.demo.Demo.ResDemo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public int getProtocol() {
        return instance.getProtocol();
      }
      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public Builder setProtocol(int value) {
        copyOnWrite();
        instance.setProtocol(value);
        return this;
      }
      /**
       * <code>optional sint32 protocol = 1;</code>
       */
      public Builder clearProtocol() {
        copyOnWrite();
        instance.clearProtocol();
        return this;
      }

      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.share.core.protocol.protobuf.demo.ResDemo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.share.core.protocol.protobuf.demo.Demo.ResDemo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.share.core.protocol.protobuf.demo.Demo.ResDemo other = (com.share.core.protocol.protobuf.demo.Demo.ResDemo) arg1;
          protocol_ = visitor.visitInt(protocol_ != 0, protocol_,
              other.protocol_ != 0, other.protocol_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  protocol_ = input.readSInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.share.core.protocol.protobuf.demo.Demo.ResDemo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.share.core.protocol.protobuf.demo.ResDemo)
    private static final com.share.core.protocol.protobuf.demo.Demo.ResDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResDemo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.share.core.protocol.protobuf.demo.Demo.ResDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ResDemo> PARSER;

    public static com.google.protobuf.Parser<ResDemo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
